name: Deploy to cloudtype
on:
  push:
    branches:
      - server-test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: rlatnsskd123/tiger-bank-back
          stage: main
          yaml: |
            name: tiger-bank-back
            app: node@20
            options:
              env:
                - name: DB_HOST
                  value: mariadb
                - name: DB_PORT
                  value: "3306"
                - name: DB_USERNAME
                  value: root
                - name: DB_PASSWORD
                  value: "1234"
                - name: DB_NAME
                  value: tiger_bank
              ports: "8080"
              start: node web.js
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
